image: python:3.8
stages:
  - lint
  - unittest
lint:
  stage: lint
  script:
    - python -m autoflake NNS/ tests/ --remove-all-unused-imports --remove-unused-variables --remove-duplicate-keys --expand-star-imports --recursive --in-place
    - python -m black NNS/ tests/ --line-length=100 --target-version py37
    - python -m isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 100 --interactive NNS/ tests/

unittest:
  stage: unittest
  script:
    - python -m pip install --no-cache-dir --user -e .[test]
    - python -m pytest --cache-clear --cov=NNS --cov-report term-missing --cov-fail-under=70 ./tests/
